### ISSUE TITLE
Specify interpreter in configuration

### ISSUE THREAD

**Issue by trangdata** [posit-dev/pyshiny-vscode#14]
Thank you for this great extension! 🌻 

Currently, the "Run" button defaults to the main interpreter (e.g. `/usr/bin/python3`). Is there a way to specify a different interpreter in Settings? I'm inside a conda environment and right now I'm just doing `shiny run --reload` and that works, but would be neat to just click a button.

**Comment by jcheng5** [comment]
(Sorry for the delay) Yes, you specify it using the Python extensions's "Select Interpreter" command. See https://code.visualstudio.com/docs/python/environments#_working-with-python-interpreters
